package Universidad.RPA.UnidadTres;
import static Universidad.RPA.modulos.*;

public class ejercicioCuatroYCinco {
    public static void main(String[] args) {
        System.out.println("Ejercicio H:");
        imprimirLinea();
        imprimirVacio();
        imprimirMitad();
        imprimirTresLineas();
        imprimirMitadMas();
        imprimirTresLineas();
        imprimirMitad();
        imprimirVacio();
        imprimirLinea();
        System.out.println("Ejercicio I:");
        imprimirLinea();
        imprimirVacio();
        imprimirMitad();
        imprimirTresLineas();
        imprimirMitadMas();
        imprimirTresLineas();
        imprimirMitad();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirLinea();
        System.out.println("Ejercicio 5:");
        System.out.println("Cancha de futbol:");
        imprimirLinea();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirMitad();
        imprimirVacio();
        imprimirVacio();
        imprimirVacio();
        imprimirLinea();
        imprimirVacio();
        imprimirVacio();
        imprimirVacio();
        imprimirMitad();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirLinea();
        System.out.println("Cancha de tennis:");
        imprimirLinea();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirLinea();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirDosLineas();
        imprimirLinea();
        System.out.println("Cancha de voley:");
        imprimirLinea();
        imprimirVacio();
        imprimirVacio();
        imprimirVacio();
        imprimirLinea();
        imprimirVacio();
        imprimirLinea();
        imprimirVacio();
        imprimirLinea();
        imprimirVacio();
        imprimirVacio();
        imprimirVacio();
        imprimirLinea();
    }
}
